import argparse
import numpy as np
from kokoro import KPipeline
import soundfile as sf
import os

parser = argparse.ArgumentParser()
parser.add_argument("text_file")
parser.add_argument("output_file")

args = parser.parse_args()

with open(args.text_file, "r", encoding="utf-8") as f:
    text = f.read()

print("Loading Kokoro Model..."); 

pipeline = KPipeline(lang_code="a")

print("Kokoro Model Loaded."); 
print("Generating Speech..."); 

generator = pipeline(
    text,
    voice="af_sky",
    speed=1.0,
)

all_audio = []

for _, _, samples in generator:
    all_audio.append(samples)

if len(all_audio) == 0:
    raise Exception("No audio generated by Kokoro.")

audio = np.concatenate(all_audio)

sf.write(args.output_file, audio, 24000)

print("Audio Saved")

print("Audio Generated Successfully")